# Generated by Django 2.0.1 on 2018-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('topic', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
